// Generated by CoffeeScript 1.4.0
(function() {

  define(['ModelItem', 'require'], function(ModelItem, require) {
    QUnit.module("insider");
    test("test in define", function() {
      return ok(true, "we are in module");
    });
    QUnit.module("ModelItem");
    QUnit.test("hola muchachos", function() {
      return ok(1 === 1, "Loading coffeescript modules");
    });
    QUnit.test("hello require", function() {
      return ok(0 === 0, "Passed?!");
    });
    test("instantiate model", function() {
      var item;
      item = new ModelItem();
      return ok(item, "Item created.");
    });
    return test("creates table on init", function() {
      var item;
      item = new ModelItem();
      return ok(item, "Item created.");
    });
  });

}).call(this);
