// Generated by CoffeeScript 1.4.0
(function() {

  define(['ModelItem'], function(ModelItem) {
    QUnit.test("hello require", function() {
      return ok(0 === 0, "Passed?!");
    });
    QUnit.module("ModelItem", {
      setup: function() {},
      teardown: function() {}
    });
    QUnit.test("instantiate model", function() {
      var item;
      item = new ModelItem({
        Name: "first item",
        Number: 1
      });
      return ok(item, "Item instantiated.");
    });
    QUnit.test("set db name", function() {
      var item, options;
      options = {
        databaseName: "TestDatabase"
      };
      item = new ModelItem({
        Name: "item with custom db name"
      }, options);
      return expect(0);
    });
    asyncTest("custom Db name", function() {
      var item, options;
      options = {
        databaseName: "TestDatabase",
        success: function() {
          start();
          return void 0;
        }
      };
      item = new ModelItem({
        Name: "first item",
        Number: 1
      });
      item.save(null, options);
      return expect(0);
    });
    asyncTest("save and load Item", function() {
      var item, onLoad, onSave, options;
      onLoad = function(model, response, options) {
        console.log("item loaded");
        ok(model.id, "Item should have an id set.");
        ok(model.get('Name') === "first item", "Item's Name should be the one set on Save.");
        return start();
      };
      onSave = function(model, response, options) {
        var id, item, loadOptions;
        console.log("model saved");
        id = model.id;
        item = new ModelItem({
          id: id
        }, options);
        loadOptions = {
          success: onLoad
        };
        return item.fetch(loadOptions);
      };
      options = {
        databaseName: "TestDatabase",
        success: onSave,
        error: function(model, tx, options) {
          return console.log("error on save");
        }
      };
      item = new ModelItem({
        Name: "first item",
        Number: 1
      });
      return item.save(null, options);
    });
    return test("two models", function() {
      var item, item2;
      item = new ModelItem();
      item2 = new ModelItem();
      return expect(0);
    });
  });

}).call(this);
