// Generated by CoffeeScript 1.4.0
(function() {

  define(['ModelItem'], function(ModelItem) {
    QUnit.test("hello require", function() {
      return ok(0 === 0, "Passed?!");
    });
    QUnit.module("ModelItem", {
      setup: function() {},
      teardown: function() {}
    });
    QUnit.test("instantiate model", function() {
      var item;
      item = new ModelItem({
        Name: "first item",
        Number: 1
      });
      return ok(item, "Item instantiated.");
    });
    test("set db name", function() {
      var item, options;
      options = {
        databaseName: "TestDatabase"
      };
      item = new ModelItem({
        Name: "item with custom db name"
      }, options);
      return expect(0);
    });
    return test("save and load Item", function() {
      var fetchResult, id, item, options;
      options = {
        databaseName: "TestDatabase"
      };
      item = new ModelItem({
        Name: "first item",
        Number: 1
      });
      item.save(null, options);
      id = item.id;
      item = new ModelItem({
        id: id
      }, options);
      fetchResult = item.fetch();
      return ok(false, "check if tables created created.");
    });
  });

}).call(this);
