// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone'], function(Backbone) {
    var ModelItem;
    ModelItem = (function(_super) {

      __extends(ModelItem, _super);

      function ModelItem() {
        return ModelItem.__super__.constructor.apply(this, arguments);
      }

      ModelItem.prototype.initialize = function() {};

      return ModelItem;

    })(Backbone.Model);
    return ModelItem;
  });

}).call(this);
