// Generated by CoffeeScript 1.4.0

/*
    Model must have properties that define its location in storage.
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', '../src/backbone-websql-table'], function(Backbone, BackboneWebsqlTable) {
    var ModelItem;
    ModelItem = (function(_super) {

      __extends(ModelItem, _super);

      function ModelItem() {
        return ModelItem.__super__.constructor.apply(this, arguments);
      }

      ModelItem.prototype.dbName = "WebsqlStore";

      ModelItem.prototype.tableName = "ModelItem";

      ModelItem.prototype.Name = "";

      ModelItem.prototype.PhoneNumber = 0;

      ModelItem.prototype.initialize = function() {
        return this.store = this.initializeDataStore();
      };

      ModelItem.prototype.createDefaultDbOptions = function() {
        var options;
        options = {};
        return options;
      };

      ModelItem.prototype.initializeDataStore = function() {
        var options, store, tableName;
        tableName = "Item";
        options = this.createDefaultDbOptions();
        options.success = function() {
          return console.log("initSuccessCallback");
        };
        options.error = function() {
          return console.log("initErrorCallback");
        };
        store = new BackboneWebsqlTable(this, options);
        return store;
      };

      return ModelItem;

    })(Backbone.Model);
    return ModelItem;
  });

}).call(this);
