// Generated by CoffeeScript 1.4.0

/*
    Model must have properties that define its location in storage.
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', '../src/backbone-websql-table'], function(Backbone, BackboneWebsqlTable) {
    var ModelItem;
    ModelItem = (function(_super) {

      __extends(ModelItem, _super);

      function ModelItem() {
        return ModelItem.__super__.constructor.apply(this, arguments);
      }

      ModelItem.prototype.defaults = {
        Name: "",
        Number: 0,
        PhoneNumber: 0
      };

      ModelItem.prototype.initialize = function(attributes, options) {
        return this.sync = BackboneWebsqlTable.sync;
      };

      ModelItem.prototype.createDefaultDbOptions = function() {
        var options;
        options = {
          databaseName: "WebsqlStore",
          tableName: "ModelItem"
        };
        return options;
      };

      ModelItem.prototype.initializeDataStore = function(options) {
        var defaultOptions, store;
        defaultOptions = this.createDefaultDbOptions();
        _.extend(options, defaultOptions);
        options.success = function() {
          return console.log("initSuccessCallback");
        };
        options.error = function() {
          return console.log("initErrorCallback");
        };
        store = new BackboneWebsqlTable(this, options);
        return store;
      };

      return ModelItem;

    })(Backbone.Model);
    return ModelItem;
  });

}).call(this);
