// Generated by CoffeeScript 1.4.0
(function() {

  QUnit.test("hola muchachos", function() {
    return ok(1 === 1, "Loading coffeescript modules");
  });

  QUnit.test("hello require", function() {
    return ok(0 === 0, "Passed?!");
  });

  test("instantiate model", function() {
    var item;
    item = new ModelItem();
    return ok(item, "Item created.");
  });

  test("creates table on init", function() {
    var item;
    item = new ModelItem();
    return ok(item, "Item created.");
  });

}).call(this);
