// Generated by CoffeeScript 1.4.0

/*

Tests
*/


(function() {

  require.config({
    paths: {
      'underscore': '../lib/underscore',
      'backbone': '../lib/backbone',
      'qunit': '../lib/qunit-1.11.0'
    },
    shim: {
      'backbone': {
        deps: ["underscore"],
        exports: "Backbone"
      },
      'qunit': {
        deps: [],
        exports: "Qunit"
      },
      'underscore': {
        exports: "_"
      }
    },
    urlArgs: "bust=" + (new Date()).getTime()
  });

  require(['BasicTests'], function(BasicTests) {});

}).call(this);
